name: CD_action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  CD_job:
    runs-on: ubuntu-latest
    environment: production
    permissions:
        id-token: write
        contents: read
    env:
      S3_MANIFEST_BUCKET: "nexabrands-prod-target"
      S3_MANIFEST_KEY: "dbt-docs/manifest.json"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r airflow/requirements_dbt_venv.txt

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Set up dbt profiles.yml
        run: |
          mkdir -p ~/.dbt
          cp .airflow/dbt/nexabrands_dbt/profiles.yml ~/.dbt/profiles.yml

      - name: Download manifest.json from S3
        run: |
          aws s3 cp s3://${{ env.S3_MANIFEST_BUCKET }}/${{ env.S3_MANIFEST_KEY }} ./manifest.json || echo "Manifest not found"

      - name: Run dbt debug
        run: dbt debug --target prod

      - name: Run dbt deps
        run: dbt deps --target prod

      - name: Run dbt build
        run: |
          if [ -f "./manifest.json" ]; then
            dbt build -s 'state:modified+' --state ./ --target prod
          else
            dbt build --target prod
          fi

      - name: Upload new manifest.json to S3
        run: |
          aws s3 cp ./target/manifest.json s3://${{ env.S3_MANIFEST_BUCKET }}/${{ env.S3_MANIFEST_KEY }}
